// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjpl4tK1S9jG514vnvSH1K_qul_rHuuNo',
    appId: '1:630802800505:web:e2e38daf0a88487660d9a8',
    messagingSenderId: '630802800505',
    projectId: 'emlak-ed397',
    authDomain: 'emlak-ed397.firebaseapp.com',
    databaseURL: 'https://emlak-ed397-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'emlak-ed397.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiYNTf4lYcTJIwl2oNW1RO1BOp1mUbK2Y',
    appId: '1:630802800505:android:b05e69164fbc58aa60d9a8',
    messagingSenderId: '630802800505',
    projectId: 'emlak-ed397',
    databaseURL: 'https://emlak-ed397-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'emlak-ed397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRe0GDh_vTAQxLi_OQxd9FlW349p6kceI',
    appId: '1:630802800505:ios:29e284f9a392d3b260d9a8',
    messagingSenderId: '630802800505',
    projectId: 'emlak-ed397',
    databaseURL: 'https://emlak-ed397-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'emlak-ed397.appspot.com',
    iosClientId: '630802800505-45gcmkav74chju6ns93h42ull2ipbqnf.apps.googleusercontent.com',
    iosBundleId: 'com.emlak.emlak',
  );
}
